name: "Build"

on:
  push:
    branches:
      - master
      - update
  pull_request:
    branches:
      - master
      - update
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm uninstall @lit/reactive-element@1.0.0-rc.4
      - run: npm dedupe
      - run: npx find-duplicate-dependencies
      - run: npm run build
